plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.1.0'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.proNutriLog.proteinCalculator'
    compileSdk 35

    defaultConfig {
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        release {
            keyAlias project.property("KEY_ALIAS")
            keyPassword project.property("KEY_PASSWORD")
            storeFile file(project.property("KEYSTORE_FILE"))
            storePassword project.property("STORE_PASSWORD")
        }
//        debug {
//            // Debug signing config, usually automatically set up by Android Studio
//            storeFile file('path/to/debug.keystore')
//        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        // Optionally, you can also add debug build types with specific configurations
//        debug {
//            signingConfig signingConfigs.debug
//            applicationIdSuffix ".debug"
//            debuggable true
//        }
    }

    // Define product flavors for different environments
    flavorDimensions += "version"
    productFlavors {
        prod {
            dimension "version"
            applicationId "com.proNutriLog.proteinCalculator"
            versionNameSuffix "-prod"
        }

        dev {
            dimension "version"
            applicationId "com.proNutriLog.proteinCalculator.dev"
            versionNameSuffix "-dev"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
//        dataBinding true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.15' // Use the latest stable version available
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.8.9'
    implementation 'androidx.navigation:navigation-ui-ktx:2.8.9'

    //Supabase
    implementation platform("io.github.jan-tennert.supabase:bom:3.1.3")
    implementation 'io.github.jan-tennert.supabase:postgrest-kt'
    implementation 'io.github.jan-tennert.supabase:auth-kt'
    implementation 'io.github.jan-tennert.supabase:realtime-kt'
    implementation "io.ktor:ktor-client-android:3.1.1"

    //Firebase
    implementation platform('com.google.firebase:firebase-bom:33.11.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-firestore:25.1.3' // Firestore library (example)


    // Jetpack Compose dependencies
    implementation 'androidx.compose.ui:ui:1.7.8'
    implementation 'androidx.compose.material:material:1.7.8'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.7.8'
    implementation 'androidx.compose.material3:material3-android:1.3.1'
    implementation 'androidx.navigation:navigation-compose:2.8.9'
    implementation 'androidx.compose.runtime:runtime-livedata:1.7.8'
    implementation 'com.google.firebase:firebase-firestore-ktx:25.1.3'
    debugImplementation 'androidx.compose.ui:ui-tooling:1.7.8'
    implementation 'androidx.activity:activity-compose:1.10.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation "androidx.constraintlayout:constraintlayout-compose:1.1.1"
    implementation "androidx.compose.foundation:foundation:1.7.8"
    implementation "androidx.compose.material:material-icons-extended:1.7.8"

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.1'
    implementation 'com.google.code.gson:gson:2.11.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
